baseurl: "/"
permalink: pretty
title: "Tom Mault"
collections_dir: collections
markdown: kramdown
highlighter: rouge

sass:
  indentWidth: 4
  style: compact
  precision: 10

google_analytics_id: false # replace with "UA-XXXX"

logo:
  logo_desktop_image: assets/images/logo/logo.svg
  logo_desktop_text: "Tom <strong>Mault</strong>"
  logo_desktop_height: "36px"
  logo_desktop_width: "36px"

social_links:
  linkedin: "https://linkedin.com/in/your-profile"
  twitter: "https://x.com/your-profile"

seo:
  meta_twitter_site: "@zerostaticio"
  meta_twitter_creator: "@zerostaticio"
  meta_og_image: "https://www.zerostatic.io/theme/jekyll-atlantic/jekyll-atlantic-screenshot.png"

plugins:
  - jekyll-environment-variables
  - jekyll-postcss
  - jekyll-paginate
  - jekyll-feed

paginate: 3
paginate_path: /blog/page:num/

collections:
  posts:
    output: true
    permalink: /blog/:name/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: "images"
    values:
      image: true
  - scope:
      path: "categories"
    values:
      layout: category
      permalink: /category/:basename/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - package.json
  - package-lock.json
  - vendor
  - LICENSE.md
  - LICENSE
  - README.md
  - .vscode
  - .gitignore
  - .liquidrc
  - postcss.config.js
  - tailwind.config.js
  - netlify.toml
